### ISSUE TITLE
老哥，问几个问题

### ISSUE THREAD

**Issue by wonktondI** [codemusik/MyBlog#1]
1.多邮箱怎么设置?设置多个smtp服务
2.博客的flag，如：选取了原创，保存不到数据库，查看博客时也不显示；手动在数据库中添加flag，可以正常展示。
老哥看见了，帮忙解答一下。谢谢啦。

**Comment by codemusik** [comment]
首先，感谢您的浏览和问题。
关于问题1，我不是很明白你的意思；
关于问题2，确实是个bug，目前已修改并提交了新代码。
再次感谢您宝贵的建议。

**Comment by codemusik** [comment]
> 1.多邮箱怎么设置?设置多个smtp服务
> 2.博客的flag，如：选取了原创，保存不到数据库，查看博客时也不显示；手动在数据库中添加flag，可以正常展示。
> 老哥看见了，帮忙解答一下。谢谢啦。

首先，感谢您的浏览和问题。
关于问题1，我不是很明白你的意思；
关于问题2，确实是个bug，目前已修改并提交了新代码。
再次感谢您宝贵的建议。

**Comment by wonktondI** [comment]
数据源可以设置多数据源。邮箱服务怎么也设置多个，比如设置了163的smtp服务，又设置qq的

**Comment by codemusik** [comment]
> 数据源可以设置多数据源。邮箱服务怎么也设置多个，比如设置了163的smtp服务，又设置qq的

不好意思，还是不明白，本博客并没有涉及到邮箱服务。
